global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api_monitoring'
    static_configs:
      - targets: ['host.docker.internal:80']

  - job_name: 'docker_host_monitoring'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
